receivers:
  otlp:
    protocols:
      grpc:
        endpoint: http://gateway.docker.internal:4317
      http:
        endpoint: http://gateway.docker.internal:4318
# Data Prepper Collector configuration
exporters:
  otlp/data-prepper:
     # Port 21890 is the default port exposed by Data Prepper.
    endpoint: http://gateway.docker.internal:21890
    insecure: true

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [otlp/data-prepper]
    metrics:
      receivers: [otlp]
      exporters: [otlp/data-prepper]
